services:
  # Web app container (Flask + Gunicorn)
  web:
    build:
      context: .
    container_name: ecommerce-webapp
    volumes:
      - .:/app
    expose:
      - "5000"  # Internal port, accessible to Nginx only
    environment:
      - DATABASE_URL=postgresql://dcarr:password@db/ecommerce_db
    depends_on:
      - db
    networks:
      - ecommerce-network

  # Database container (PostgreSQL)
  db:
    image: postgres:13
    container_name: ecommerce-db
    environment:
      - POSTGRES_USER=dcarr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommerce_db
    volumes:
      - ecommerce_db_data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # Nginx container
  nginx:
    image: nginx:latest
    container_name: ecommerce-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app  # optional, for static files
    ports:
      - "80:80"  # Only Nginx binds to port 80 on the host
    depends_on:
      - web
    networks:
      - ecommerce-network

volumes:
  ecommerce_db_data:

networks:
  ecommerce-network:
    driver: bridge
